index:
   path: /
   controller: App\Controller\BasicController::index
   methods: GET

# Person 

person_list:
    path: /Person
    controller: App\Controller\PersonController::list
    methods: GET

person_new:
    path: /Person/new
    controller: App\Controller\PersonController::new
    methods: GET|PUT

person_edit:
    path: /Person/{id}/edit
    controller: App\Controller\PersonController::edit
    methods: GET|PUT

person_delete:
    path: /Person/{id}/delete
    controller: App\Controller\PersonController::delete
    methods: DELETE

# Group

group_list:
    path: /Group
    controller: App\Controller\GroupOfPeopleController::list
    methods: GET

group_new:
    path: /Group/new
    controller: App\Controller\GroupOfPeopleController::new
    methods: GET|PUT

group_edit:
    path: /Group/{id}/edit
    controller: App\Controller\GroupOfPeopleController::edit
    methods: GET|PUT

group_delete:
    path: /Group/{id}/delete
    controller: App\Controller\GroupOfPeopleController::delete
    methods: DELETE

